### ISSUE TITLE
Veigar

### ISSUE THREAD

**Issue by fluut** [berbb/PortAIO#114]
He often tries to go for champion hits with q in laneclear mode when a minion blocks the path and is often unkillable, so it won't pierce through and that q is useless. the cage seems to have either bad pred or just low hitchance, it tries to cast the cage right on them when there's a 0.75s delay and that'll never work. Sometimes uses ults randomly without them being killable, probably uses old ult calculation.

**Comment by berbb** [comment]
I updated it so that it will actually use R only on killable targets _if_ you have the option selected in the menu. 

I also updated the LC hitchance so that it hits the minions accurately, it's not suppose to try to harass with Q during LC.

Also, if you've used other Veigar scripts you'd notice that the E is fairly bad on all of them, it's not really anything a script can predict with amazing accuracy.
