### ISSUE TITLE
Insec on azir ?

### ISSUE THREAD

**Issue by IlikeBaconLol** [berbb/PortAIO#134]
I mean i don't find any way to do the insec on azir 

Could u help me

Excuse me to worry u

And nice AIO !

**Comment by berbb** [comment]
Make sure your Target Selector looks like this : http://i.imgur.com/H1z33gr.png

Then, choose your insec mode, I personally enjoy using "last key press" because it allows me to place where I want to insec. If you're using "Last Key Press" then press "Insec Point Key" or 'T' anywhere on the map to choose where you want to insec. Then, double click your target to select them and hold the "Insec Selected" Key which is 'Y' at default. Congrats, you've done an insec.
