### ISSUE TITLE
Console error for champions not casting spells

### ISSUE THREAD

**Issue by DrogonRocks** [berbb/PortAIO#136]
So, i started having this problem after latest core update from elobuddy ( yesterday 05/05/2016 everything was working perfect with all champions), now some champions don't use skills at all, don't know why, i found that reinstalling EB made it work for 1-2 matches but after that the problem started again
I think is a bug with OKTW supported champions, here is the console i got in 3 games ( velkoz, syndra and ekko ) only using portaio
console:
ekko: http://prnt.sc/b16l4k
syndra: http://prnt.sc/b16la7
velkoz: http://prnt.sc/b16l7j

it's weird because after reinstall i got velkoz to work, but now it doesn't, don't know what could be the problem.
*Edit#2
tried with yasuo, same error, so its not only oktw, because yasuo is valravesharp
console: http://prnt.sc/b17cl7
*What i've tried? 
-Deleting everything that has to do with EB and reinstalling it over and over
-only using champion addon without utility in portaio menu

Berbb i know you are not getting this error but some of us have, im trying to provide the most detailed info i can so you can tell me what's wrong 
Also, i don't know if it has something to do, but can this happen because im playing "One For All" ?

_**FINAL EDIT: Just read your message on discord, you can close this, will use EB standalone addons for One for all, besides that i will keep using portaio <3  **_

**Comment by DrogonRocks** [comment]
nevermid, the problem started again, i think is a bug with OKTW supported champions, here is the console i got in 3 games ( velkoz, syndra and ekko ) only using portaio
console:
ekko: http://prnt.sc/b16l4k
syndra: http://prnt.sc/b16la7
velkoz: http://prnt.sc/b16l7j

it's weird because after reinstall i got velkoz to work, but now it doesn't, don't know what could be the problem.

**Comment by berbb** [comment]
It's because One For All conflicts with the making of the menu so the rest of the script is not loaded.

In the OKTW scripts some of them have menus like : 
"[ ] Auto Q"
"[ ] Harass : Fiora"
"[ ] Harass : Blitzcrank"
"[ ] Harass : Xin Zhao"
"[ ] Harass : Xerath"
"[ ] Harass : Kalista"

But in One For All the menu is :
"[ ] Auto Q"
"[ ] Harass : Kalista"
"[ ] Harass : Kalista" [Addon breaks right here because there is already an entry of Kalista]
"[ ] Harass : Kalista"
"[ ] Harass : Kalista"
"[ ] Harass : Kalista"

And this breaks the addon because there can't be more than one menu entry with the exact same ID's.
