### ISSUE TITLE
ElUtilitySuite HealthTracker FPS decline.

### ISSUE THREAD

**Issue by lyn690697457** [berbb/PortAIO#140]
It can cause a serious decline in FPS, do not know why. I try to close the remaining functional but still leaving it severely dropped frames.
‘ Please check it

**Comment by lyn690697457** [comment]
But as soon as I turned off this feature, FPS is no longer dropped.
Why is that T-T
I do not know if anyone and I have the same problem

**Comment by berbb** [comment]
It's been an issue for a while and I just might remove it as it's fucking useless.

**Comment by inphratiic** [comment]
health trackers and damage indicators will always drop ur FPS ( a bit ) because their functions are getting called at every tick ( it's like u calling ur mom every single second non-stop to ask her always the same questions). If u don't have a nice PC setup u should disable it. It could  also be code that isn't optimized (messy code)

**Comment by lyn690697457** [comment]
I think this feature should be removed
