### ISSUE TITLE
elutilitysuite problem and champion attack issue and also target selector problem

### ISSUE THREAD

**Issue by princedraven2** [berbb/PortAIO#173]
hi, the elutilitysuite is giving false health bars. the champions reach no health and there still not dead so therefor they still have health and the bars are messed up by utilitysuite because i tried portaio without the suite and the bars work fine. Also another problem is champions not attacking even when in range, they dont attack the very moment they become in range. Whenever i play draven with tyler1, draven will wait like a few seconds or more to attack instead of attacking instantly. No attacking at all or delayed attacking happens quiet a bit. The target selection is also weird, the champion will begin attacking another enemy thats close by but the other one should obviously be attacked instead. I'm not sure if this is a elobuddy target selector problem, maybe its just that shitty i dont know.

**Comment by berbb** [comment]
There's nothing wrong with the ElUtilitySuite Healh Bars, they're just out of place,I just need to modify the X values a little bit and it'll show the whole health bar. I'll fix it asap.

The Draven issue seems to be an Orbwalker error because the script/AIO doesn't control what the champion hits or not, it's the EB orbwalker.

Same with the Target Selector error, unfortunately also a EB issue. But it could be easily fixed by selecting a target.

**Comment by princedraven2** [comment]
im not sure if sdkpredictioner made things any better for draven..im playing him right now, kinda seems better hmm...

**Comment by berbb** [comment]
Alright, fixed the ElUtilitySuite Health Bar placement for most champions, some champs may still have the cooldown bar broken because they have a special bar like Jhin. If you have any more problems feel free to report them :)

**Comment by princedraven2** [comment]
is there any possible way to make a modified version of the elobuddy orbwalker and put l# code in it? There is someone on the elobuddy forums that made a custom orbwalker that overrides the elobuddy orbwalker so elobuddy has to use his instead. Could you do that?

**Comment by berbb** [comment]
It's possible but EB's orbwalker isn't open source so I can't copy and paste it and add modifications. And porting the L# Orbwalker alone doesn't work at all because some parts of EB's core is not at all the same as L#'s. Even if I were to successfully portL #'s Orbwalker, I would have to modify all of the ported addons to be compatible with L#'s orbwalker so it works the same as if you were using L#.

**Comment by princedraven2** [comment]
hate to say it..but that probably is what should of been done in the first place : / oh well

**Comment by berbb** [comment]
I did lol, like I said it didn't work at all so I just made it compatible with EB orb.
