### ISSUE TITLE
PortAIO - Preferred/Recommended Settings

### ISSUE THREAD

**Issue by Xelamats** [berbb/PortAIO#201]
PortAIO - Preferred/Recommended Settings
---
Hello everyone,

As we always get asked for the best prediction method/addon to use for the champion (if there is multiple) I've decided to create a Google Sheet where all this information will be available. This will make it so if someone is to ask we can just link them this and move on.

-----

**Have an idea on which addons/prediction method you think is best?**
- Post here with what addon/prediction is best and for what champion.
- Leave your reason why you believe this (other prediction method misses a lot, other addon doesn't do this, etc.)

----
**Link** (view only): https://docs.google.com/spreadsheets/d/1wsKssIY8bY2mQC0l4JhMa-sOFurgleZvOLALnUX8mQI/edit?usp=sharing

Currently empty :dancers: ; Awaiting suggestions.
- Please only post if you have a suggestion.

**Comment by dankmemer420** [comment]
Seems like a good idea and maybe useful to some people, good luck!

**Comment by Xelamats** [comment]
@dankmemer420 

Added something at the bottom of the post just for you.

**Comment by 3ackdoor** [comment]
Vayne - ChallengerSeries
- Q > Sharpshooter (it suits for my play)
- E > Synx's Auto Carry (because you can setting how much accuracy so basically you max it and it will try to Q>E when possible)
- Enable Don't use AA in Stealth (when you vs more than 3 you can wreck them)
- default another settings
