### ISSUE TITLE
Veigar R is a little off

### ISSUE THREAD

**Issue by rman200** [berbb/PortAIO#205]
Well, just played veigar with everything standard and his ultimate's calculations seems a little off (only used 3 times in a 28 min match) 
Could be something with SpellDmg as I dont see anything wrong with the code, but please look into it anyway

//Predicitions are AMAZING, dude. Keep up the good job!!
//This is the ONLY addon we need on EB right now, srsly I deleted all the others lol (no evade because fuck bans)

**Comment by berbb** [comment]
The damage was off because the L# Common Damage Calc was off, so I'll have to wait until they update it so I can port it over. As a substitute I changed the damage calculations from L# Common (since its outdated) to EB's (hopefully not outdated). 

If it is still off with the latest update I just pushed then EB's Damage Calculations for Veigar is off also so we'll just have to wait for an update.
