### ISSUE TITLE
Issues - Caitlyn

### ISSUE THREAD

**Issue by Xelamats** [berbb/PortAIO#21]
I've only been able to test it during one game of ranked and these are the problems that arose.

----

**FPS Drops**; I normally have around 130fps while using other addons and with this I had 50 - 60 all game.

**W usage is lacking**. Rarely did it ever place it during a combo (other addon I was using was doing this as they would step it in most of the time)

**Q usage is random sometimes**. If the enemies were to the right, it shot to the left. Seemed to fix this by always making sure to place my mouse toward the enemy so I would assume it has something to do with it still shooting towards the mouse? Wasn't pressing Q manually during that time.

----

Other than those, it works amazingly. Thank you for releasing this, btw. If you ever need any help, I cannot code, I will lend you all the time I have.

**Comment by berbb** [comment]
Thanks for the kind comments, will check Cait out today, thanks. :)

**Comment by berbb** [comment]
I've checked it out and I've been getting some FPS drops also, I'm not entirely sure what it is, I've pushed an update but it might not improve the FPS.

The W usage is lacking because it doesn't cast it on combo, it only casts W on TP, CC, and in a bush, or to interrupt, the original OKTW doesn't have a "on combo" W usage either,
