### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by spvrtan** [berbb/PortAIO#219]
Yasuo W in yasuopro doesnt windwall the correct way.

Vayne R in VHR doesnt automatically use in combo with x enemies around.

Darius Q makes him stand still in combo, also doesnt use W.

Nidalee Q prediction is waaaaaaay off (idk if there'll ever be a fix for that cos i havent seen a decent Q in any nid script)

Olaf doesnt cast W in combo and also throws Q at an enemys feet instead of behind them.

Aatrox doesnt work at all

ELTrundle casts E in front of the enemy, rather than behind them to stop them escaping.

Viktor E is EXTREMELY buggy in waveclear, it will stutterstep about 5x per sec until it reaches X amount of minions it can cast it on.

ELSinged doesnt Cast E in combo.

Pantheon cancels E in combo mode after using it for 0.5 seconds.

Maokai is just hella buggy in general, barely uses Q or W in combo, R cancels itself after enemy leaves the ult radius, doesnt auto attack in combo or wave clear modes.

These are the champions i've currently tested that have issues, keep up the great work :)

**Comment by berbb** [comment]
YasuoPro windwall should be fixed, if it's still happening reply to this with what skill it's fucking up on. Thanks for the bug report will check it out.

**Comment by berbb** [comment]
Vayne R > VHR doesnt automatically R in combo, it will only R if it can pull an R > Q.

**Comment by berbb** [comment]
Fixed Darius.

* I haven't pushed the updates yet, I'm pushing it all in one.

**Comment by berbb** [comment]
- Can't do much about Nidalee Q, prediction issue.
- Olaf fixed

**Comment by spvrtan** [comment]
Good job buddy :+1:

**Comment by Sharpino** [comment]
More issues:
-twitch casts e late + add damage drawing please
-malz casts q behind enemy + casts r late

**Comment by hardique** [comment]
Berbb,what is the best prediction for VHR?
And is it possible to add SDK?

**Comment by berbb** [comment]
- Aatrox doesn't seem to have any problems at all.
- Fixed Trundle Retarded Pillar
- Fixed Viktor LC & JG Stutter
- Singed does use E but it doesn't use the W>E combo to root.
- Pantheon Fixed
- Mao'Kai is fixed up, it added an option so that you can cancel ult manually when there's no target. If Q is still not casting make sure to set the max range to < 500 and turn off "Only Q on Immobile".

If any of these problems keep happening then just clear appdata, try again and if its still happening respond to this issue or make a new one.

**Comment by berbb** [comment]
@Sharpino ... Which Twitch...

And I'll check out Malz.
