### ISSUE TITLE
Riven's Burst

### ISSUE THREAD

**Issue by Lurker7** [berbb/PortAIO#24]
Hey Berbb :)
While playing Riven with ur script I have noticed that her burst combo is completely broken :/
First of all it should use her stun (W) right after flashing towards the selected enemy during combo, but right now she unfortunately uses her other abilities instead before using W.
Can you change that please?
With the burst working properly, this will literally be a total freelo Riven script, even in diamond elo :D
Damn, just noticed that Fiora script is also highly bugged, so pointing it out in this line.
BTW, love your work bro, keep it up :)
We are all very grateful for that amazing AIO ;)

**Comment by KiriharaSenpai** [comment]
yea thats a problem of original addon i think go nechirito riven topic and you ll see what im saying

**Comment by Lurker7** [comment]
Ohh ok, but maybe Berbb can fix it somehow hopefully anyway <3
Well at least he can realise that Fiora is broken based on my post and a good Fiora script can make u win games easily :D, so i think this feedback is quite valuable anyway :)

**Comment by KiriharaSenpai** [comment]
okay gonna try fiora and report back for you

**Comment by KiriharaSenpai** [comment]
yea fiora has some issue

**Comment by berbb** [comment]
Yeah, the only thing I do is port it and fix minor issues, because I'm not sure how it even works, Nechrito will have to fix it, sorry, but maybe if I dual-port Hoola riven it'll be better(?) :)

But, about the Fiora issue, I've been having that issue and I'll completely port another one soon.

Thanks for the feedback, I'll work on it this weekend.

**Comment by Muse30** [comment]
I though the best riven in l# was kurisu xD
