### ISSUE TITLE
Zed Script

### ISSUE THREAD

**Issue by DrHouse12** [berbb/PortAIO#251]
Zed script not working. Please fix it if u can ,

**Comment by Muse30** [comment]
????? more info pls.. and which zed?

**Comment by DrHouse12** [comment]
Ahh okay, i didnt saw that i can change scripts.. Valvare not working.

**Comment by berkerbey** [comment]
Hey there, Can u port Korean Zed Assembly?

**Comment by berbb** [comment]
@berkerbey I remember Korean Zed because it was the best Zed, but as of now it hasn't been updated in about 6 months+, I can try porting it but there may be some needed fixes to it.

@DrHouse12 I just tested in a custom and its working just fine, doing the combo correctly, using spells and everything.

**Comment by SidaRevamped** [comment]
PLEASE PORT KOREAN ZED THE BEST ZED SCRIPT IN THE HISTORY OF SCRIPTING , sorry for caps

**Comment by Muse30** [comment]
I thought it was really buggy because is not updated
