### ISSUE TITLE
Orbwalker with Vayne scripts

### ISSUE THREAD

**Issue by Acheiro** [berbb/PortAIO#255]
Hey,
I've encountered a strange problem. My orbwalker was randomly stop working almost all the time. Once it worked, once not only when I used PortAIO Vayne - VHR. But I heard it's not only Vayne issue. Could you check this?

**Comment by KiriharaSenpai** [comment]
yea for me vhr has some issue sometimes it doesnt even attack enemy
but challenger series works so good

**Comment by hardique** [comment]
same to me with VHR.
Also increasing distance for i_am_gosu not working (E push distance)

**Comment by BigPhalus** [comment]
thought i would take it upon myself to explain the issue a bit more, problem with the orbwalker on Vayne- VHR, only occurs during combo, basically what happens is orbwalker stops attacking (everything else works, just no auto attacks going off), what i have found to fix the issue is clicking on a minion and pressing farm mode and then continuing with combo mode, however this is far from being optimal.

**Comment by berbb** [comment]
Pushed some fixes that should fix the Orbwalker issue. And fixed Hi_Im_Gosu's E Push Distance.
