### ISSUE TITLE
Why do you remove L# Orbwalker?

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#27]
It's work really good. Why do you removed it?
And does it possible to use L# Target selector with EB orbwalker?

**Comment by berbb** [comment]
To put it in short it was just too much to update. I'd spend so many hours working on it that I'd rejected a bit of sleep (people in discord know this haha) but another reason was the same reason I stopped developing it before, it was taking time from updating the rest of PortAIO. 

I try to not let the github issues exceed 6-10 issues but now because I'm so far behind that its at 14...

**Comment by lightduy94** [comment]
And you give up + deleted all your hard worked? :pepe:
Btw, really really thank you for this awesome AIO! I'll miss L# Orbwalker and especially L# Target Selector!
