### ISSUE TITLE
Can i do that?

### ISSUE THREAD

**Issue by SidaRevamped** [berbb/PortAIO#276]
oktw Syndra have a very bad logic , can i just import kortatu logic in oktw , i know the goal of portAi is just port the assemblies , but man i can realy improve syndra hard if i use gagong and kortatu logic with oktw Syndra .

**Comment by lgndz** [comment]
I mean... if you can make that work why not just write it up and call it your own..?

Custom PortAIO script "D

**Comment by SidaRevamped** [comment]
because it's not from me , if i took kortatu logic  for farm , gagong logic for ult , Hikigaya logic for w and oktw logic for q and put it in one addon , nothing is from me

**Comment by lgndz** [comment]
Oh. Well. Stitching it together would be you - but I feel you. 

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Tue, Jun 14, 2016 at 2:16 PM -0400, "SidaRevamped" <notifications@github.com> wrote:












because it's not from me , if i took kortatu logic  for farm , gagong logic for ult , Hikigaya logic for w and oktw logic for q and put it in one addon , nothing is from me

**Comment by Muse30** [comment]
well you can do it and try it yourself and see if is working good, we will add it
