### ISSUE TITLE
MoonyLux errors

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#28]
`========================================
Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at LeagueSharp.Common.PredictionOutput.get_CastPosition()
   at MoonLux.Program.AutoShield()
   at MoonLux.Program.Game_OnUpdate(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()
========================================
`

**Comment by berbb** [comment]
This shouldn't impact the game, all the script is trying to do is predict your allies movements so that the W will hit them as if it were an enemy thus shield them, prediction-like. 

But times when your ally dies and it tries to auto shield them it will throw that error because it can't find your allies position on the server because he's dead.
