### ISSUE TITLE
Khazix bug no pun :^)

### ISSUE THREAD

**Issue by BuckFrandon** [berbb/PortAIO#450]
I got this while playing kha'zix http://puu.sh/pOIdX/9e77a0600b.png 

I would get the welcome to portaio message but nothing would be loaded in but the elobuddy defaults.

**Comment by berbb** [comment]
This is definitely a PortAIO bug, more likely a Berb.Common bug. So this isn't a Kha'Zix bug but an evade bug. But that evade is going toward LeagueSharp.Data for some reason where all the.json files are at.

Something definitely fucked up but it won't be worth searching for because its like a one-time bug almost, you shouldn't experience it again.
