### ISSUE TITLE
LCS Lucian

### ISSUE THREAD

**Issue by dankmemer420** [berbb/PortAIO#586]
When weaving spells it'll use E > AA > AA > Q instead of E > AA > Q > AA and so fourth, I've cleared appdata and it was happening before the L# orbwalker update.

EDIT: I think it does this when i manually E.

**Comment by berbb** [comment]
This is hard to explain but I could see why it does this when you manually E. The only time LCS Lucian will do the weaving is when the Orbwalker is the one doing the auto attacking, it won't register your manual input because the Orbwalker has to be the one checking for the AA.

https://github.com/berbb/PortAIO/blob/master/Champion/Lucian/Program.cs#L109 - The code for that logic.
