### ISSUE TITLE
Viktor is Obvious ? 

### ISSUE THREAD

**Issue by NentoR** [berbb/PortAIO#594]
I know this question is not for here but you Berbb have more experience than me that's why i will ask you. Is Viktor obvious for scripting ? I wanna play safe. If i use SebbyBanWars + LittleHumanizer and 215 OrbWalker delay on L# with not high prediction my Viktor will be obvious ?

**Comment by KiriharaSenpai** [comment]
depend on how do you use it if u dont miss a skillshot all the game time ofc it obvious but play smart in lane phase miss some skillshot with your hand and dont take all kill let your team to take them

**Comment by Lemonadez** [comment]
Viktor script is obvious. No matter how much Humanizer you want. Because If you play Legit. You would not be able to do something like Viktor running away (Orbwalking) and Casting Extended Laser at the opponent, while your running away. That impossible to do because if You play Legit Viktor, You will stop moving to cast an Extended laser.. But if You keep moving and casting Extended Laser while moving around. That easily script. I tried It already. Anyone who just try to deny it, never play Viktor legit. You can also see any High Elo player play Viktor and Compare it to yourself, You will see you do better than them.

**Comment by Muse30** [comment]
I play viktor in high elo (Diamond 2) with scripts.. never been called out

@Lemonadez you sound like bronze

**Comment by lyn690697457** [comment]
Poor I am bronze 2

**Comment by Lemonadez** [comment]
@Muse30 try play Viktor Script. Do cast Extended Laser while walking backwards. <- Impossible :O

**Comment by inphratiic** [comment]
@Lemonadez gues u can just click further back and then aim the E to the guy xD not that hard
