### ISSUE TITLE
vSeries sona problems

### ISSUE THREAD

**Issue by Sharpino** [berbb/PortAIO#599]
-not using heal
-using r to gapclose when off

**Comment by berbb** [comment]
Fixed heal, no wonder why heal wasn't working, the console error was huge because of it, it caused FPS drops, get it for me next time it helps me a lot : 
http://image.prntscr.com/image/57f1af6a5e7f4da4872c4d5390102861.png

R only casts on killsteal, interruptable, gapclose, and combo. It must've used R trying to interrupt or something.
