### ISSUE TITLE
Tristana issue

### ISSUE THREAD

**Issue by saladinaazir** [berbb/PortAIO#67]
occaisionally, the orbwalker will stop working in laneclear untill you attack a champion in combo, which then fixes the problem. Is this an EB problem?

**Comment by berbb** [comment]
Alright, I think this happens because whenever the addon see's a minion that has Trist's E charge it will force the Orbwalker to attack that minion, and it will keep forcing the orbwalker to attack that minion (event when it's dead) until the Orbwalker forces another target. like in combo. 

I've update so that if there is is no minion or champion around with Trist's E charge it will delete the forced target which should allow you to use the Orbwalker normally. Thanks for reporting this.
