### ISSUE TITLE
Orbwalker suggestion

### ISSUE THREAD

**Issue by inphratiic** [berbb/PortAIO#8]
So when u have some free time u could think about porting a orbwalker since the EB one seems to have some problems atm

**Comment by lgndz** [comment]
To be fair, I dont know if it is the ORBW itself that is the biggest issue, or the Preds that were ported over that these use. There seems to be a big issue with OKTW and the champs it uses so it could be the Common.Pred is having issues?

**Comment by inphratiic** [comment]
Probably not Common.Pred since u can change pred's inside OKTW and it still performs badly using every single one available ( Spred , common, OKTW and SDK). Most likely some broken function or check

**Comment by lgndz** [comment]
You are correct. Didn't think of that. 

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Thu, May 19, 2016 at 4:24 AM -0700, "inphratiic" <notifications@github.com> wrote:












Probably not Common.Pred since u can change pred's inside OKTW and it still performs badly using every single one available ( Spred , common, OKTW and SDK). Most likely some broken function or check

**Comment by berbb** [comment]
I tried before and its not the same at all, I was expecting the code to work but it just doesn't. Plus porting an Orbwalker will mean I will have to tweak every single champions to work with the ported orbwalker.
