### ISSUE TITLE
Maintaining AIO

### ISSUE THREAD

**Issue by Requital** [berbb/PortAIO#95]
hey maybe its a stupid question but arent keeping L# orb and Ts easier to maintain than Eb ones? Like you just copy the code of script or am i wrong?

**Comment by SidaRevamped** [comment]
your so wrong

**Comment by Haxory** [comment]
damn son, prank went too far XD

**Comment by berbb** [comment]
Definitely not easier. When I ported the L# TargetSelector and Orbwalker the only thing that was actually working post-port was the TargetSelector. 

I spent about 3 days fixing up the Orbwalker and making it work with EloBuddy and it just didn't work out. Now if we still kept it then it would be more work for me because then i'd have to update the calculations each patch and make it it's working.
